# Generated by Django 4.2.1 on 2023-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paritechapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
